<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Azure.Monitor.OpenTelemetry.AspNetCore" VersionOverride="1.4.0" />
    <PackageReference Include="Azure.Monitor.OpenTelemetry.Exporter" VersionOverride="1.7.0" />
    <PackageReference Include="coverlet.collector" VersionOverride="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="JunitXml.TestLogger" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" VersionOverride="18.4.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting" />
    <PackageReference Include="Moq" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" />
    <PackageReference Include="OpenTelemetry.Exporter.InMemory" VersionOverride="1.15.3" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Process" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../../src/SimpleOpenTelemetry/SimpleOpenTelemetry.csproj" />
  </ItemGroup>

</Project>
