<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AWSSDK.CloudWatch" />
    <PackageReference Include="AWSSDK.CloudWatchLogs" />
    <PackageReference Include="AWSSDK.Core" />
    <PackageReference Include="AWSSDK.XRay" />
    <PackageReference Include="AwsSignatureVersion4" />
    <PackageReference Include="OpenTelemetry.Extensions.AWS" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AWS" />
    <PackageReference Include="OpenTelemetry.Instrumentation.Http" />
    <PackageReference Include="OpenTelemetry.Resources.AWS" />
    <PackageReference Include="OpenTelemetry.Sampler.AWS" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\..\..\src\SimpleOpenTelemetry\SimpleOpenTelemetry.csproj" />
  </ItemGroup>

</Project>
