<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <LangVersion>12</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <EnableNETAnalyzers>true</EnableNETAnalyzers>
    <AnalysisLevel>latest</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>

    <!-- NuGet Package Properties -->
    <PackageId>SimpleOpenTelemetry</PackageId>
    <Authors>Chad Paynter</Authors>
    <Company></Company>
    <Description>A lightweight, low-code .NET library for configuring OpenTelemetry code-based instrumentation via IConfiguration, supporting both generic-host and standalone apps. Pre-tested example config snippets and configurations for major cloud platforms can be dropped in easily and the underlying OpenTelemetryBuilder stays accessible for adding settings via code.</Description>
    <PackageTags>opentelemetry;telemetry;monitoring;traces;observability</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <Copyright>Copyright © Chad Paynter</Copyright>
    <RepositoryUrl>https://github.com/degero/SimpleOpenTelemetry</RepositoryUrl>
    <RepositoryType>git</RepositoryType>
    <PackageProjectUrl>https://github.com/degero/SimpleOpenTelemetry</PackageProjectUrl>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <MinVerTagPrefix>v</MinVerTagPrefix>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
  </PropertyGroup>

  <PropertyGroup>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <None Include="README.nuget.md" Pack="true" PackagePath="README.md" />
    <None Include="../../LICENSE" Pack="true" PackagePath="" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="SimpleOpenTelemetry.Tests" />
    <InternalsVisibleTo Include="SimpleOpenTelemetry.IntegrationTests" />
    <InternalsVisibleTo Include="DynamicProxyGenAssembly2" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="MinVer" PrivateAssets="All" />
    <PackageReference Include="Microsoft.SourceLink.GitHub" PrivateAssets="All" />
    <PackageReference Include="OpenTelemetry" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" />
    <PackageReference Include="OpenTelemetry.Exporter.OpenTelemetryProtocol" />
  </ItemGroup>

</Project>
