name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.0.x'

      - name: Build
        run: dotnet build SimpleOpenTelemetry.sln -c Release --no-incremental

      - name: Test
        run: dotnet test SimpleOpenTelemetry.sln -c Release --no-build --verbosity normal --logger:"junit;LogFilePath=${{ github.workspace }}/testresults/{assembly}.xml"  --collect:"XPlat Code Coverage" --results-directory ./coverage

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: ./coverage/**/coverage.cobertura.xml
          token: ${{ secrets.CODECOV_TOKEN }}

      - name: Upload test results to Codecov
        uses: codecov/test-results-action@v1
        with:
          files: ./testresults/*.xml
          token: ${{ secrets.CODECOV_TOKEN }}