name: Lint
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  dotnet-format:
    permissions:
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "10.0.x"
      - run: dotnet format src/SimpleOpenTelemetry/SimpleOpenTelemetry.csproj --verify-no-changes --verbosity diagnostic

  # TODO enable prettier
  # prettier:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - run: npx prettier --check "**/*.{json,yaml,yml,md}"
